services:
  postgres:
    image: postgres:16.2
    container_name: postgres-booksapi
    restart: always
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - 5432:5432
    volumes:
      - ../postgres:/var/lib/postgresql/data


volumes:
  postgres:
